title: Nooshin Bahador
description: 
url: "https://nbahador.github.io"
logo: /assets/img/image.jpg
baseurl: ""  # Leave this empty unless you're using a subpath
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
