title: Nooshin Bahador
logo: /assets/img/image.jpg
description: Some information about me.
url: "https://nbahador.github.io"
baseurl: ""  # Leave this empty unless you're using a subpath
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
